-- MySQL Script generated by MySQL Workbench
-- Thu Oct 13 09:49:30 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`questions` (
  `id` INT NOT NULL,
  `content` VARCHAR(45) NULL,
  `answers_idanswers` INT NOT NULL,
  `check_id` INT NOT NULL,
  PRIMARY KEY (`id`, `answers_idanswers`, `check_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`answers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`answers` (
  `id` INT NOT NULL,
  `content` VARCHAR(45) NULL,
  `questions_id` INT NOT NULL,
  `questions_answers_idanswers` INT NOT NULL,
  `is_right` INT NOT NULL,
  `check_id` INT NOT NULL,
  PRIMARY KEY (`id`, `questions_id`, `questions_answers_idanswers`, `is_right`, `check_id`),
  CONSTRAINT `fk_answers_questions1`
    FOREIGN KEY (`questions_id` , `questions_answers_idanswers`)
    REFERENCES `mydb`.`questions` (`id` , `answers_idanswers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`students` (
  `idstudents` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `questions_idquestions` INT NOT NULL,
  `questions_answers_idanswers` INT NOT NULL,
  `check_id` INT NOT NULL,
  PRIMARY KEY (`idstudents`, `questions_idquestions`, `questions_answers_idanswers`, `check_id`),
  CONSTRAINT `fk_students_questions1`
    FOREIGN KEY (`questions_idquestions` , `questions_answers_idanswers`)
    REFERENCES `mydb`.`questions` (`id` , `answers_idanswers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`test` (
  `id` INT NOT NULL,
  `data` VARCHAR(45) NULL,
  `check_id` INT NOT NULL,
  PRIMARY KEY (`id`, `check_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`test_has_questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`test_has_questions` (
  `test_id` INT NOT NULL,
  `questions_id` INT NOT NULL,
  `questions_answers_idanswers` INT NOT NULL,
  PRIMARY KEY (`test_id`, `questions_id`, `questions_answers_idanswers`),
  CONSTRAINT `fk_test_has_questions_test1`
    FOREIGN KEY (`test_id`)
    REFERENCES `mydb`.`test` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_test_has_questions_questions1`
    FOREIGN KEY (`questions_id` , `questions_answers_idanswers`)
    REFERENCES `mydb`.`questions` (`id` , `answers_idanswers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`students_has_test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`students_has_test` (
  `students_idstudents` INT NOT NULL,
  `students_questions_idquestions` INT NOT NULL,
  `students_questions_answers_idanswers` INT NOT NULL,
  `test_id` INT NOT NULL,
  PRIMARY KEY (`students_idstudents`, `students_questions_idquestions`, `students_questions_answers_idanswers`, `test_id`),
  CONSTRAINT `fk_students_has_test_students1`
    FOREIGN KEY (`students_idstudents` , `students_questions_idquestions` , `students_questions_answers_idanswers`)
    REFERENCES `mydb`.`students` (`idstudents` , `questions_idquestions` , `questions_answers_idanswers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_students_has_test_test1`
    FOREIGN KEY (`test_id`)
    REFERENCES `mydb`.`test` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`check`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`check` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `answers_id` INT NOT NULL,
  `answers_questions_id` INT NOT NULL,
  `answers_questions_answers_idanswers` INT NOT NULL,
  `answers_is_right` INT NOT NULL,
  `answers_check_id` INT NOT NULL,
  `questions_id` INT NOT NULL,
  `questions_answers_idanswers` INT NOT NULL,
  `questions_check_id` INT NOT NULL,
  `students_idstudents` INT NOT NULL,
  `students_questions_idquestions` INT NOT NULL,
  `students_questions_answers_idanswers` INT NOT NULL,
  `students_check_id` INT NOT NULL,
  `test_id` INT NOT NULL,
  `test_check_id` INT NOT NULL,
  PRIMARY KEY (`id`, `answers_id`, `answers_questions_id`, `answers_questions_answers_idanswers`, `answers_is_right`, `answers_check_id`, `questions_id`, `questions_answers_idanswers`, `questions_check_id`, `students_idstudents`, `students_questions_idquestions`, `students_questions_answers_idanswers`, `students_check_id`, `test_id`, `test_check_id`),
  CONSTRAINT `fk_check_answers1`
    FOREIGN KEY (`answers_id` , `answers_questions_id` , `answers_questions_answers_idanswers` , `answers_is_right` , `answers_check_id`)
    REFERENCES `mydb`.`answers` (`id` , `questions_id` , `questions_answers_idanswers` , `is_right` , `check_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_check_questions1`
    FOREIGN KEY (`questions_id` , `questions_answers_idanswers` , `questions_check_id`)
    REFERENCES `mydb`.`questions` (`id` , `answers_idanswers` , `check_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_check_students1`
    FOREIGN KEY (`students_idstudents` , `students_questions_idquestions` , `students_questions_answers_idanswers` , `students_check_id`)
    REFERENCES `mydb`.`students` (`idstudents` , `questions_idquestions` , `questions_answers_idanswers` , `check_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_check_test1`
    FOREIGN KEY (`test_id` , `test_check_id`)
    REFERENCES `mydb`.`test` (`id` , `check_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
